---

name: 'Lock Threads'

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '28 0 * * 2'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v4
        with:
          issue-inactive-days: '90'
          pr-inactive-days: '90'
          log-output: true
